import type { AdvancedLesson } from './advanced';

export const advancedExtraLessons: AdvancedLesson[] = [
  {
    slug: 'event-loop-deep-dive', category: 'Async JavaScript', title: 'Event Loop بعمق: Call Stack وQueues وMicrotasks',
    summary: 'افهم كيف يستطيع JavaScript تنفيذ أعمال غير متزامنة رغم وجود Call Stack واحد، ولماذا Promise وsetTimeout لا يعملان بالطريقة نفسها.',
    definition: 'Event Loop هي الآلية التي تنسق بين تنفيذ JavaScript المتزامن وبين نتائج العمليات غير المتزامنة. JavaScript تنفذ الكود على Call Stack، وعندما تنتهي المهمة الحالية يمكن للـEvent Loop أن تسمح للمهام الجاهزة بالدخول وفق قواعد الأولوية الخاصة بالبيئة. في المتصفح وNode.js توجد تفاصيل إضافية، لكن الفكرة الأساسية هي: لا يتم إيقاف الـstack انتظارًا لعملية I/O؛ البيئة تنفذ العمل خارج المسار المباشر ثم تسلم النتيجة عندما يحين دورها.',
    why: 'من دون فهم Event Loop ستبدو نتائج ترتيب console.log وPromise وsetTimeout غريبة. هذا الفهم أساسي جدًا في Node.js لأن الخادم يعتمد على I/O غير المتزامن حتى يخدم اتصالات كثيرة دون إنشاء thread JavaScript مستقل لكل طلب.',
    terms: [['Call Stack','المكان الذي تُنفذ فيه استدعاءات JavaScript الحالية وفق مبدأ LIFO.'],['Task / Macrotask','مهمة مجدولة مثل بعض مؤقتات البيئة وأحداث I/O.'],['Microtask','مهمة ذات أولوية أعلى نسبيًا مثل callbacks الخاصة بالـPromise.'],['I/O','Input/Output مثل قراءة ملف أو انتظار الشبكة.'],['Event Loop','المنسق الذي يسمح باستمرار تنفيذ المهام الجاهزة بعد انتهاء العمل الحالي.']],
    code: 'console.log("A");\n\nsetTimeout(() => console.log("B"), 0);\n\nPromise.resolve().then(() => console.log("C"));\n\nconsole.log("D");',
    output: 'A\nD\nC\nB',
    lineByLine: ['A تنفذ فورًا على Call Stack.','setTimeout يسجل callback ليُنفذ لاحقًا ولا يوقف السطر التالي.','Promise.then يسجل Microtask عند تحقق الـPromise.','D تنفذ قبل مغادرة المهمة الحالية.','بعد انتهاء الكود المتزامن يتم تنفيذ Microtask C قبل مهمة المؤقت B في البيئات المعتادة.'],
    realWorld: 'في API يستقبل طلبًا ثم ينتظر قاعدة بيانات، لا تريد أن تجمد الخادم حتى تعود قاعدة البيانات. تستمر JavaScript في معالجة أعمال أخرى، وعند جاهزية النتيجة يعود callback أو Promise continuation إلى مسار التنفيذ.',
    underTheHood: 'التفاصيل الدقيقة تختلف بين المتصفح وNode.js. Node.js تستخدم libuv لإدارة كثير من أعمال I/O والـevent loop phases، بينما V8 مسؤول عن تنفيذ JavaScript وMicrotask machinery. لذلك عبارة "Node.js فيها Thread واحد" تبسيط: JavaScript execution الأساسي على thread واحد، لكن البيئة تستخدم threads ومكونات نظام لتنفيذ بعض الأعمال.',
    pitfalls: ['القول إن setTimeout(..., 0) يعني التنفيذ فورًا.','الاعتقاد أن Promise تجعل العملية نفسها متزامنة.','نسيان أن كثرة Microtasks يمكن أن تؤخر مهام أخرى.','الخلط بين Event Loop وV8؛ V8 محرك JavaScript وليس Node.js كلها.'],
    exercise: 'توقع ترتيب A وB وC وD في مثال يحتوي على Promise.then وsetTimeout وconsole.log، ثم شغله في Node.js وقارن توقعك.',
    answer: 'console.log("A"); setTimeout(()=>console.log("B"),0); Promise.resolve().then(()=>console.log("C")); console.log("D");\n// A D C B'
  },
  {
    slug: 'node-streams', category: 'Node.js', title: 'Streams: التعامل مع البيانات الكبيرة بكفاءة',
    summary: 'تعلم لماذا Streams أفضل من تحميل ملف ضخم كاملًا إلى الذاكرة، وما الفرق بين Readable وWritable وTransform.',
    definition: 'Stream هي abstraction لمعالجة البيانات على أجزاء صغيرة متتابعة بدل انتظار وجود البيانات كلها. في Node.js توجد Readable Streams للقراءة، Writable للكتابة، Duplex للاتجاهين، وTransform التي تقرأ وتنتج بيانات محولة. هذا النموذج مناسب للملفات والشبكات والفيديو والـHTTP bodies.',
    why: 'لو قرأت ملفًا حجمه عدة جيجابايت باستخدام readFile فقد تحتاج إلى الاحتفاظ ببيانات ضخمة في الذاكرة. Stream تسمح بمعالجة chunk ثم التخلص منه، فتقلل memory pressure وتبدأ النتائج في الوصول قبل اكتمال المصدر بالكامل.',
    terms: [['Chunk','جزء صغير من البيانات يصل إلى الـstream.'],['Readable','مصدر يمكن القراءة منه.'],['Writable','وجهة يمكن الكتابة إليها.'],['Transform','Stream تعدل البيانات أثناء مرورها.'],['Backpressure','آلية تمنع المصدر السريع من إغراق الوجهة الأبطأ.']],
    code: 'import { createReadStream, createWriteStream } from "node:fs";\n\nconst input = createReadStream("input.txt");\nconst output = createWriteStream("copy.txt");\n\ninput.pipe(output);\noutput.on("finish", () => console.log("Copied"));',
    output: 'Copied',
    lineByLine: ['createReadStream لا يحمل الملف كاملًا دفعة واحدة.','createWriteStream يفتح وجهة للكتابة التدريجية.','pipe يربط المصدر بالوجهة وينقل chunks.','finish يعني أن الـWritable انتهت من استقبال البيانات وكتابة ما لديها.'],
    realWorld: 'رفع ملف إلى خادم أو إرسال ملف PDF كبير للعميل مثال ممتاز. يمكنك تمرير البيانات تدريجيًا بدل إنشاء Buffer ضخم في الذاكرة.',
    underTheHood: 'Streams تعتمد على buffering وتنظيم تدفق البيانات. عندما تصبح الوجهة أبطأ، backpressure تساعد في إبطاء المصدر أو تنظيم القراءة بدل تراكم chunks بلا حدود. لهذا pipe مفيدة لأنها تنسق المصدر والوجهة بدل كتابة منطق إدارة التدفق يدويًا.',
    pitfalls: ['استخدام readFile لكل ملف ضخم بلا حاجة.','تجاهل أخطاء stream.','الاعتقاد أن pipe يعني أن البيانات كلها أصبحت في الذاكرة.','عدم فهم backpressure عند بناء pipelines مخصصة.'],
    exercise: 'أنشئ برنامجًا ينسخ ملفًا باستخدام createReadStream وcreateWriteStream وجرّب تسجيل حجم كل chunk.',
    answer: 'const input=createReadStream("input.txt"); input.on("data", chunk=>console.log(chunk.length)); input.pipe(createWriteStream("copy.txt"));'
  },
  {
    slug: 'node-buffers', category: 'Node.js', title: 'Buffer: البيانات الثنائية في Node.js',
    summary: 'افهم لماذا يحتاج Node.js إلى Buffer للتعامل مع bytes والملفات والشبكات، وكيف يختلف عن string وArray.',
    definition: 'Buffer هو نوع خاص في Node.js يمثل منطقة من الذاكرة تحتوي على bytes خام. JavaScript في الأصل تتعامل بسهولة مع النصوص والقيم، لكن الشبكات والملفات قد تنتج بيانات ثنائية لا يصح اعتبارها نصًا. Buffer يوفر طريقة مباشرة للتعامل مع تلك bytes.',
    why: 'ستقابل Buffer عند قراءة ملفات، التعامل مع TCP/HTTP، الصور، التشفير وبعض APIs. فهمه يمنع أخطاء الترميز وتحويل البيانات ويجعلك تفهم العلاقة بين bytes وstrings.',
    terms: [['Byte','وحدة من 8 bits ويمكنها تمثيل قيمة من 0 إلى 255.'],['Encoding','طريقة تفسير bytes كنص مثل UTF-8.'],['Buffer','حاوية bytes في Node.js.'],['Binary Data','بيانات ليست مجرد نص قابل للقراءة البشرية.']],
    code: 'const buffer = Buffer.from("Hello", "utf8");\n\nconsole.log(buffer);\nconsole.log(buffer.toString("utf8"));\nconsole.log(buffer.length);',
    output: '<Buffer 48 65 6c 6c 6f>\nHello\n5',
    lineByLine: ['Buffer.from يحول النص إلى bytes باستخدام UTF-8.','console.log يعرض التمثيل الست عشري للbytes.','toString يعيد تفسير bytes كنص UTF-8.','length تعطي عدد bytes، وقد تختلف عن عدد الأحرف في النصوص متعددة البايت.'],
    realWorld: 'عند رفع صورة، البيانات التي تصل ليست نصًا عاديًا. Node.js يمكنها استقبالها كbytes أو stream ثم حفظها أو تمريرها إلى خدمة تخزين.',
    underTheHood: 'Buffer مبني فوق ArrayBuffer ومفاهيم ذاكرة منخفضة المستوى، ويوفر APIs محسنة للتعامل مع البيانات الثنائية. Encoding مهم لأن الحرف الواحد قد يحتاج أكثر من byte في UTF-8.',
    pitfalls: ['اعتبار buffer.toString() مناسبًا لكل أنواع البيانات الثنائية.','الخلط بين عدد الأحرف وعدد bytes.','تحويل ملفات ثنائية إلى نص ثم فقدان البيانات بسبب encoding خاطئ.'],
    exercise: 'أنشئ Buffer من النص "محمد" وقارن buffer.length بعدد الأحرف، ثم فسّر لماذا القيمتان مختلفتان.',
    answer: 'const text="محمد"; const b=Buffer.from(text,"utf8"); console.log(text.length,b.length); // 4 chars, 8 bytes تقريبًا لهذا النص'
  },
  {
    slug: 'node-events', category: 'Node.js', title: 'EventEmitter: نموذج الأحداث في Node.js',
    summary: 'افهم كيف تبني APIs تعتمد على events وكيف تستمع وتطلق أحداثًا باستخدام EventEmitter.',
    definition: 'EventEmitter هو pattern/API في Node.js يسمح لكائن بإطلاق events بأسماء محددة، بينما تسجل أجزاء أخرى من البرنامج listeners لتنفيذها عند وقوع الحدث. كثير من APIs في Node.js تستخدم هذا النموذج، خصوصًا streams وبعض موارد النظام.',
    why: 'فهم events يسهل عليك قراءة Node APIs ويشرح كيف يمكن لكائن واحد إشعار عدة أجزاء من التطبيق دون ربطها ببعضها مباشرة.',
    terms: [['Emitter','الكائن الذي يطلق event.'],['Listener','دالة تستجيب لحدث.'],['emit','إطلاق حدث مع بيانات اختيارية.'],['on','تسجيل listener يتكرر عند كل occurrence.'],['once','تسجيل listener يعمل مرة واحدة.']],
    code: 'import { EventEmitter } from "node:events";\n\nconst bus = new EventEmitter();\nbus.on("user:created", user => {\n  console.log(`Welcome ${user.name}`);\n});\n\nbus.emit("user:created", { name: "Osama" });',
    output: 'Welcome Osama',
    lineByLine: ['أنشأنا EventEmitter ليكون event bus صغيرًا.','on يسجل listener لاسم user:created.','emit يطلق الحدث ويرسل object كوسيط.','listener يستقبل object ويطبع الاسم.'],
    realWorld: 'يمكن استخدام events داخل نظام logging أو مراقبة دورة حياة خدمة. لكن في الأنظمة الكبيرة لا تجعل EventEmitter بديلًا عشوائيًا للـdatabase أو message broker.',
    underTheHood: 'EventEmitter يحتفظ بقائمة listeners مرتبطة بأسماء الأحداث ويستدعيها عند emit. التنفيذ المحلي لا يعني أن الحدث أصبح distributed؛ إذا احتجت التواصل بين عمليات مختلفة ستحتاج آلية أخرى مثل queue أو broker.',
    pitfalls: ['استخدام event bus ضخم يجعل تتبع تدفق البيانات صعبًا.','نسيان إزالة listeners في حالات معينة.','الاعتقاد أن EventEmitter يعمل عبر servers مختلفة تلقائيًا.','تجاهل special handling لحدث error في EventEmitter.'],
    exercise: 'أنشئ EventEmitter باسم orderBus، وأطلق event باسم order:paid يرسل رقم الطلب، وسجل رسالة عند وصوله.',
    answer: 'const bus=new EventEmitter(); bus.on("order:paid", id=>console.log(`Paid: ${id}`)); bus.emit("order:paid",123);'
  },
  {
    slug: 'node-process-env', category: 'Node.js', title: 'process وEnvironment Variables',
    summary: 'تعلم كيف يتعامل Node.js مع معلومات العملية وبيئة التشغيل ولماذا لا يجب وضع الأسرار داخل الكود.',
    definition: 'process كائن عالمي يوفر معلومات وتحكمًا متعلقًا بعملية Node.js الحالية، مثل argv وcwd وplatform وexit. process.env يحتوي على environment variables التي توفرها بيئة التشغيل. هذه القيم مهمة للإعدادات التي تختلف بين development وproduction مثل database URL وAPI keys.',
    why: 'المشروع الحقيقي لا يجب أن يضع كلمات المرور والمفاتيح داخل source code. Environment variables تسمح بتغيير الإعدادات عند النشر دون تعديل الكود.',
    terms: [['process','يمثل عملية Node.js الحالية.'],['process.env','كائن يحتوي على environment variables المتاحة للعملية.'],['argv','وسائط سطر الأوامر.'],['cwd','مجلد التشغيل الحالي.'],['Secret','معلومة حساسة مثل API key أو database password.']],
    code: 'const port = Number(process.env.PORT ?? 3000);\nconst mode = process.env.NODE_ENV ?? "development";\n\nconsole.log({ port, mode });\nconsole.log(process.cwd());',
    output: '{ port: 3000, mode: "development" }\n/path/to/project',
    lineByLine: ['نقرأ PORT من البيئة.','?? يستخدم 3000 فقط عندما تكون القيمة null أو undefined.','Number يحول النص القادم من environment إلى number.','NODE_ENV تحدد نمط التشغيل إن كانت موجودة.','cwd تعرض مجلد التشغيل الحالي.'],
    realWorld: 'في Vercel أو Docker أو VPS يمكن ضبط DATABASE_URL وAUTH_SECRET وPORT من إعدادات البيئة بدل تخزينها في Git.',
    underTheHood: 'Environment variables تصل للعملية من نظام التشغيل أو منصة التشغيل. Node.js تعرضها عبر process.env. أغلب القيم تكون strings، لذلك validation والتحويل مسؤولية التطبيق.',
    pitfalls: ['رفع .env الذي يحتوي أسرارًا إلى Git.','نسيان أن process.env.PORT نص.','افتراض وجود متغير environment دائمًا.','وضع secret في NEXT_PUBLIC_ أو أي متغير مخصص للعميل دون فهم أنه قد يصبح مكشوفًا.'],
    exercise: 'اكتب قراءة لـPORT وDATABASE_URL مع قيم افتراضية مناسبة للتطوير، ثم تحقق أن PORT رقم صحيح.',
    answer: 'const port=Number(process.env.PORT??3000); if(!Number.isInteger(port)||port<=0) throw new Error("Invalid PORT"); const db=process.env.DATABASE_URL; if(!db) throw new Error("DATABASE_URL is required");'
  },
  {
    slug: 'node-http-request-response', category: 'Node.js', title: 'HTTP Request وResponse من الداخل',
    summary: 'افهم ما الذي يصل إلى الخادم داخل request وما الذي يجب أن تعيده في response قبل استخدام Express أو Next.js APIs.',
    definition: 'HTTP protocol يحدد طريقة تبادل الرسائل بين client وserver. Request يحتوي method وURL وheaders وbody، بينما response يحتوي status code وheaders وbody. Node.js توفر http module منخفض المستوى يسمح ببناء server مباشرة.',
    why: 'Frameworks مثل Express وNext.js تخفي كثيرًا من التفاصيل، لكن فهم HTTP يجعلك تعرف لماذا توجد GET وPOST وstatus codes وheaders وJSON وcookies.',
    terms: [['Method','نوع العملية مثل GET وPOST وPUT وPATCH وDELETE.'],['Headers','بيانات وصفية عن الطلب أو الرد مثل Content-Type.'],['Status Code','رقم يصف نتيجة الطلب مثل 200 أو 404 أو 500.'],['Body','المحتوى الرئيسي للرسالة.'],['Content-Type','يصف صيغة body مثل application/json.']],
    code: 'import { createServer } from "node:http";\n\nconst server = createServer((req, res) => {\n  res.statusCode = 200;\n  res.setHeader("Content-Type", "application/json; charset=utf-8");\n  res.end(JSON.stringify({ ok: true, method: req.method, url: req.url }));\n});\n\nserver.listen(3000);',
    output: 'GET / → {"ok":true,"method":"GET","url":"/"}',
    lineByLine: ['createServer ينشئ HTTP server ويستقبل callback لكل request.','req يمثل الطلب القادم.','statusCode يحدد نتيجة الاستجابة.','Content-Type يخبر العميل أن body بصيغة JSON.','JSON.stringify يحول object إلى string يمكن إرساله.','res.end ينهي response ويرسل body.','listen يجعل الخادم يستمع على port 3000.'],
    realWorld: 'عندما تستدعي frontend endpoint مثل /api/users، المتصفح يرسل HTTP request والخادم يقرر status وheaders وbody ثم يعيد response.',
    underTheHood: 'HTTP يعمل فوق TCP في HTTP/1.1 التقليدي، بينما HTTP/2 وHTTP/3 لها تفاصيل نقل مختلفة. تطبيق Node.js لا يحتاج معرفة كل طبقات البروتوكول ليستخدمها، لكنه يستفيد من فهم حدود request/response والـheaders والـstatus.',
    pitfalls: ['إرجاع JSON object مباشرة دون serialization في APIs منخفضة المستوى.','إرسال status 200 لكل الأخطاء.','نسيان Content-Type.','اعتبار req.body موجودًا تلقائيًا في node:http؛ parsing للbody يحتاج منطقًا أو framework.'],
    exercise: 'اكتب server يعيد 404 إذا كان URL ليس /، ويعيد JSON بسيطًا إذا كان /health.',
    answer: 'if(req.url!=="/health"){res.statusCode=404;return res.end("Not Found");} res.setHeader("Content-Type","application/json"); res.end(JSON.stringify({status:"ok"}));'
  },
  {
    slug: 'node-error-handling', category: 'Node.js', title: 'Error Handling: try/catch وAsync Errors',
    summary: 'تعلم الفرق بين throw وreturning errors ولماذا تحتاج العمليات غير المتزامنة إلى استراتيجية واضحة لمعالجة الفشل.',
    definition: 'Error handling هو تصميم طريقة لاكتشاف الأخطاء وتمريرها والتعامل معها دون ترك التطبيق في حالة غير متوقعة. JavaScript توفر throw وtry/catch/finally، ومع Promises يمكن استخدام catch أو try/catch مع await.',
    why: 'تطبيق backend يتعامل مع ملفات وقواعد بيانات وشبكات ومدخلات مستخدم. الفشل طبيعي، لذلك الكود الاحترافي لا يفترض أن كل عملية ستنجح.',
    terms: [['throw','يرفع exception بدل إرجاع قيمة عادية.'],['try','كتلة تحتوي الكود الذي قد يرمي exception.'],['catch','مكان استقبال exception ومعالجته.'],['finally','كود ينفذ بعد نجاح أو فشل try/catch.'],['Operational Error','فشل متوقع نسبيًا مثل timeout أو ملف غير موجود.']],
    code: 'async function loadUser() {\n  try {\n    const response = await fetch("https://example.com/user");\n    if (!response.ok) throw new Error(`HTTP ${response.status}`);\n    return await response.json();\n  } catch (error) {\n    console.error("Failed to load user", error);\n    throw error;\n  }\n}',
    output: 'عند النجاح: يعاد user object.\nعند الفشل: يسجل الخطأ ثم يعاد رفعه للطبقة الأعلى.',
    lineByLine: ['try يحيط بالعملية التي قد تفشل.','await ينتظر نتيجة Promise دون تحويل البرنامج كله إلى blocking thread.','response.ok يسمح بالتحقق من status قبل محاولة قراءة البيانات.','throw ينشئ مسار فشل واضحًا.','catch يسجل الخطأ أو يحوله إلى شكل مناسب.','throw error يعيد الخطأ للـcaller بدل إخفائه.'],
    realWorld: 'في API route قد تلتقط خطأ قاعدة البيانات ثم ترسل 500 للعميل، بينما تسجل التفاصيل الداخلية في logs دون كشف stack trace أو secrets للمستخدم.',
    underTheHood: 'Promise rejection لا تدخل catch المتزامن إلا إذا كنت تستخدم await داخل try. أما Promise غير المنتظر فيجب التعامل معها عبر catch أو await لاحق. هذا من أهم أسباب unhandled rejections.',
    pitfalls: ['catch ثم تجاهل الخطأ تمامًا.','إرسال رسالة خطأ داخلية تحتوي أسرارًا للعميل.','استخدام try/catch حول كل سطر بلا تصميم واضح للطبقات.','نسيان await أو catch في Promise.'],
    exercise: 'اكتب دالة getJson(url) تستخدم fetch، تتحقق من response.ok، وتعيد JSON أو ترمي Error برسالة مفيدة.',
    answer: 'async function getJson(url){ const res=await fetch(url); if(!res.ok) throw new Error(`HTTP ${res.status}`); return res.json(); }'
  },
  {
    slug: 'node-architecture-modules', category: 'Node.js', title: 'Modules وArchitecture في مشروع Node.js',
    summary: 'انتقل من ملف واحد إلى تنظيم احترافي يفصل routes وservices وrepositories وconfig بدل خلط كل شيء معًا.',
    definition: 'Module هو وحدة مستقلة من الكود يمكنها تصدير قيم واستيرادها من وحدات أخرى. في Node.js الحديثة يمكنك استخدام ES Modules عبر import/export، كما توجد CommonJS عبر require/module.exports. Architecture هي طريقة تنظيم هذه الوحدات والمسؤوليات.',
    why: 'المشروع الصغير قد يعمل في ملف واحد، لكن مع نموه يصبح التعديل والاختبار صعبين. فصل المسؤوليات يجعل كل جزء أسهل في الفهم والاختبار والاستبدال.',
    terms: [['Module','ملف أو وحدة لها حدود واستيرادات وتصديرات.'],['Service','طبقة تحتوي منطق business/application.'],['Repository','طبقة تتعامل مع مصدر البيانات مثل database.'],['Route/Controller','طبقة تستقبل HTTP وتحوّل الطلب إلى استدعاء مناسب.'],['Separation of Concerns','فصل المسؤوليات حتى لا تعتمد كل التفاصيل على بعضها.']],
    code: '// user.service.ts\nexport async function getUser(id:string){\n  return userRepository.findById(id);\n}\n\n// user.route.ts\nimport { getUser } from "./user.service";\n\nexport async function handler(req,res){\n  const user = await getUser(req.params.id);\n  return res.json(user);\n}',
    output: 'HTTP layer يستقبل الطلب → service ينفذ business logic → repository يتعامل مع database → النتيجة تعود للـHTTP layer.',
    lineByLine: ['service لا يحتاج معرفة تفاصيل HTTP.','route تستدعي service بدل كتابة SQL أو business rules بداخلها.','repository يمثل الحد الفاصل مع database.','كل طبقة يمكن اختبارها واستبدال تفاصيلها بسهولة أكبر.'],
    realWorld: 'في Next.js أو Node API كبير يمكنك تنظيم features مثل users وorders ثم فصل database access عن business logic وعن HTTP handlers.',
    underTheHood: 'Modules تمنعك من جعل كل المتغيرات global. import/export تبني dependency graph يستخدمه runtime أو bundler وفق البيئة. Architecture ليست قاعدة واحدة؛ الهدف أن تكون dependencies واضحة وأن تتغير التفاصيل دون كسر كل النظام.',
    pitfalls: ['إنشاء مجلدات كثيرة بلا سبب حقيقي.','وضع database logic داخل route مباشرة.','عمل circular dependencies بين modules.','فصل الطبقات شكليًا مع بقاء كل طبقة معتمدة على تفاصيل الأخرى.'],
    exercise: 'صمم feature users في ثلاثة ملفات: user.route.ts وuser.service.ts وuser.repository.ts، وحدد وظيفة كل ملف في سطرين.',
    answer: 'route: HTTP input/output. service: business rules. repository: database operations.\n// لا تضع SQL داخل route ولا status codes داخل repository.'
  }
];
