export type Lesson={slug:string;category:string;title:string;summary:string;explanation:string;code:string;output:string;tip:string;takeaways:string[]};
export const lessons:Lesson[]=[
{slug:'variables',category:'JavaScript',title:'المتغيرات: let و const و var',summary:'كيف تخزن القيم وتختار طريقة تعريف المتغير المناسبة.',explanation:'المتغير هو اسم يشير إلى قيمة. في JavaScript الحديثة استخدم const عندما لا تحتاج لإعادة إسناد المتغير، وlet عندما ستغيّر قيمته. var أسلوب قديم وله نطاق مختلف.',code:'const name = "Osama";\nlet score = 10;\nscore += 5;\nconsole.log(name, score);',output:'Osama 15',tip:'ابدأ بـ const كخيار افتراضي، وانتقل إلى let عند الحاجة.',takeaways:['const لا يسمح بإعادة الإسناد.','let مناسب للقيم المتغيرة.','تجنب var في الكود الحديث.']},
{slug:'scope',category:'JavaScript',title:'النطاق Scope',summary:'افهم أين يمكن الوصول إلى المتغير داخل البرنامج.',explanation:'النطاق يحدد الأماكن التي يمكن للكود فيها الوصول إلى المتغير. let وconst لهما Block Scope، بينما var له Function Scope.',code:'if (true) {\n  const message = "داخل البلوك";\n  console.log(message);\n}',output:'داخل البلوك',tip:'كلما صغّرت نطاق المتغير كان الكود أسهل في الفهم.',takeaways:['Block Scope مع let وconst.','Function Scope مع var.','النطاق يقلل الاستخدام العشوائي للمتغيرات.']},
{slug:'functions',category:'JavaScript',title:'الدوال Functions',summary:'وحدات قابلة لإعادة الاستخدام لتنفيذ مهمة محددة.',explanation:'الدالة تجمع خطوات مرتبطة تحت اسم واحد. يمكنها استقبال parameters وإرجاع return value.',code:'function add(a, b) {\n  return a + b;\n}\nconsole.log(add(4, 6));',output:'10',tip:'اجعل كل دالة مسؤولة عن مهمة واحدة واضحة.',takeaways:['الدالة تستقبل معاملات.','return يعيد قيمة.','إعادة الاستخدام تقلل تكرار الكود.']},
{slug:'arrow-functions',category:'JavaScript',title:'Arrow Functions',summary:'صيغة مختصرة للدوال مع سلوك مختلف لـ this.',explanation:'دوال الأسهم توفر صيغة مختصرة، والأهم أنها لا تنشئ this خاصًا بها بل ترثه من السياق المحيط.',code:'const multiply = (a, b) => a * b;\nconsole.log(multiply(3, 4));',output:'12',tip:'ممتازة للـ callbacks والعمليات القصيرة.',takeaways:['صيغة مختصرة.','لا تملك this خاصًا بها.','مناسبة للـ callbacks.']},
{slug:'arrays',category:'JavaScript',title:'المصفوفات Arrays',summary:'تخزين مجموعة من القيم والتعامل معها بكفاءة.',explanation:'Array بنية بيانات مرتبة. ستستخدمها كثيرًا مع map وfilter وfind وreduce.',code:'const numbers = [1, 2, 3, 4];\nconst doubled = numbers.map(n => n * 2);\nconsole.log(doubled);',output:'[2, 4, 6, 8]',tip:'تعلّم map وfilter وfind وreduce جيدًا.',takeaways:['المصفوفة مرتبة.','map تنشئ مصفوفة جديدة.','filter تختار عناصر وفق شرط.']},
{slug:'objects',category:'JavaScript',title:'الكائنات Objects',summary:'تجميع بيانات مرتبطة في properties وmethods.',explanation:'الكائن يمثل شيئًا له خصائص وسلوك، ويظهر في APIs وبيانات المستخدم وإعدادات التطبيقات.',code:'const user = { name: "Sara", age: 24 };\nconsole.log(user.name);',output:'Sara',tip:'افهم dot notation وdestructuring لأنهما شائعان جدًا.',takeaways:['البيانات تخزن في properties.','يمكن للكائن احتواء methods.','Destructuring يسهل استخراج القيم.']},
{slug:'callbacks',category:'Async JavaScript',title:'Callbacks',summary:'تمرير دالة إلى دالة أخرى لتنفيذها لاحقًا.',explanation:'Callback هي دالة تُمرر إلى دالة أخرى. في العمليات غير المتزامنة قد تنفذ بعد انتهاء المهمة.',code:'setTimeout(() => {\n  console.log("Done");\n}, 500);',output:'Done',tip:'مهمة لفهم تاريخ async، لكن Promises وasync/await أسهل في المشاريع الحديثة.',takeaways:['الدالة يمكن تمريرها كقيمة.','قد تنفذ لاحقًا.','التداخل الزائد يصعّب القراءة.']},
{slug:'promises',category:'Async JavaScript',title:'Promises',summary:'طريقة منظمة لتمثيل نتيجة عملية غير متزامنة.',explanation:'Promise تبدأ pending ثم تصبح fulfilled أو rejected. يمكنك التعامل معها عبر then/catch أو async/await.',code:'const promise = Promise.resolve("Success");\npromise.then(value => console.log(value));',output:'Success',tip:'فكر في Promise كوعد بنتيجة ستتوفر لاحقًا.',takeaways:['pending ثم fulfilled/rejected.','then للنجاح.','catch للأخطاء.']},
{slug:'async-await',category:'Async JavaScript',title:'async / await',summary:'صيغة تجعل التعامل مع Promises أكثر وضوحًا.',explanation:'الدالة async تعيد Promise، وawait ينتظر نتيجة Promise داخل async function. استخدم try/catch لمعالجة الأخطاء.',code:'async function getData() {\n  const result = await Promise.resolve("Data");\n  console.log(result);\n}\ngetData();',output:'Data',tip:'استخدم try/catch مع await عندما تحتاج معالجة أخطاء واضحة.',takeaways:['async تعيد Promise.','await ينتظر Promise.','try/catch مناسب للأخطاء.']},
{slug:'closures',category:'Async JavaScript',title:'Closures',summary:'الدالة تحتفظ بإمكانية الوصول إلى نطاقها الخارجي.',explanation:'الدالة الداخلية تستطيع الاحتفاظ بالوصول إلى المتغيرات من النطاق الخارجي حتى بعد انتهاء تنفيذ ذلك النطاق.',code:'function counter() {\n  let count = 0;\n  return () => ++count;\n}\nconst next = counter();\nconsole.log(next());\nconsole.log(next());',output:'1\n2',tip:'Closures مهمة لفهم state والـcallbacks.',takeaways:['الدالة تحفظ lexical environment.','يمكن إخفاء state.','تظهر كثيرًا مع callbacks.']},
{slug:'event-loop',category:'Async JavaScript',title:'Event Loop',summary:'كيف يدير JavaScript المهام غير المتزامنة.',explanation:'JavaScript تنفذ الكود على call stack، وتنسق البيئة عمليات I/O والـcallbacks عبر event loop. هذا أساس قوة Node.js.',code:'console.log("A");\nsetTimeout(() => console.log("B"), 0);\nconsole.log("C");',output:'A\nC\nB',tip:'setTimeout(...,0) لا يعني التنفيذ فورًا.',takeaways:['Call stack ينفذ الكود.','Callbacks تنتظر دورها.','I/O غير المتزامن أساس قوة Node.js.']},
{slug:'what-is-nodejs',category:'Node.js',title:'ما هو Node.js؟',summary:'بيئة تشغيل JavaScript خارج المتصفح مبنية حول V8.',explanation:'Node.js Runtime مفتوح المصدر ومتعدد المنصات. يستخدم V8 لتنفيذ JavaScript خارج المتصفح ويضيف APIs مثل filesystem وnetworking وprocess.',code:'console.log("Running JavaScript with Node.js");\nconsole.log(process.version);',output:'Running JavaScript with Node.js\nvXX.X.X',tip:'Node.js ليس لغة جديدة ولا Framework؛ هو Runtime.',takeaways:['Runtime وليس لغة.','يستخدم V8.','يوفر APIs خارج المتصفح.']},
{slug:'v8',category:'Node.js',title:'محرك V8',summary:'محرك JavaScript عالي الأداء من Google يستخدمه Chrome وNode.js.',explanation:'V8 مكتوب أساسًا بـC++ وينفذ ECMAScript وWebAssembly. Node.js يستخدمه لتشغيل JavaScript خارج المتصفح.',code:'const result = 20 + 22;\nconsole.log(result);',output:'42',tip:'V8 هو المحرك، وNode.js هو البيئة التي تضيف APIs.',takeaways:['V8 JavaScript engine.','يستخدمه Chrome وNode.js.','Node يضيف APIs فوق المحرك.']},
{slug:'browser-vs-node',category:'Node.js',title:'Node.js مقابل المتصفح',summary:'نفس اللغة، لكن بيئتان مختلفتان.',explanation:'المتصفح يقدم window وdocument وDOM. Node.js لا يملك DOM لكنه يوفر filesystem وprocess وserver APIs.',code:'// Browser\nconsole.log(window.location.href);\n\n// Node.js\nconsole.log(process.platform);',output:'Browser: URL\nNode.js: win32/linux/darwin',tip:'JavaScript هي اللغة؛ البيئة تحدد APIs المتاحة.',takeaways:['document موجود في المتصفح.','process من Node.js.','نفس اللغة لا تعني نفس البيئة.']},
{slug:'modules',category:'Node.js',title:'Modules: import و export',summary:'تقسيم التطبيق إلى ملفات ووحدات قابلة لإعادة الاستخدام.',explanation:'Node.js الحديث يدعم ES Modules باستخدام import/export، كما يدعم CommonJS في السياقات المناسبة.',code:'export const add = (a, b) => a + b;\n\nimport { add } from "./math";\nconsole.log(add(2, 3));',output:'5',tip:'قسّم الكود حسب المسؤوليات بدل ملف واحد ضخم.',takeaways:['export يعرّض قيمة.','import يستوردها.','Modules تساعد على التنظيم.']},
{slug:'npm',category:'Node.js',title:'npm و package.json',summary:'إدارة الحزم والاعتماديات والـscripts.',explanation:'npm مدير حزم شائع في منظومة Node.js. package.json يصف المشروع واعتمادياته وأوامر التشغيل.',code:'npm init -y\nnpm install express\nnpm run dev',output:'Project initialized\nDependencies installed\nDev script started',tip:'افهم dependencies وdevDependencies وlockfile.',takeaways:['package.json تعريف المشروع.','npm يدير الحزم.','scripts تختصر أوامر متكررة.']},
{slug:'http-server',category:'Node.js',title:'HTTP Server',summary:'إنشاء خادم HTTP بسيط باستخدام Node.js.',explanation:'Node يوفر وحدة http لإنشاء servers تستقبل requests وتعيد responses. فهم request/response أساس مهم قبل frameworks.',code:'import { createServer } from "node:http";\n\nconst server = createServer((req, res) => {\n  res.end("Hello Node.js");\n});\n\nserver.listen(3000);',output:'Server listening on http://localhost:3000',tip:'افهم status codes وheaders وrequest/response.',takeaways:['server يستقبل requests.','response ترجع البيانات.','listen يفتح المنفذ.']},
{slug:'environment-variables',category:'Node.js',title:'Environment Variables',summary:'فصل الإعدادات السرية والمتغيرة عن الكود.',explanation:'متغيرات البيئة تمرر إعدادات مثل DATABASE_URL أو API keys دون وضعها في source code. لا ترفع الأسرار إلى GitHub.',code:'const port = process.env.PORT ?? "3000";\nconsole.log(`Server port: ${port}`);',output:'Server port: 3000',tip:'استخدم .env محليًا وSecrets في منصة الاستضافة.',takeaways:['process.env للوصول للقيم.','لا تضع secrets في Git.','NEXT_PUBLIC_ في Next.js يعني متاحًا للعميل.']}
];
